#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Servidor iperf e Stress
### END INIT INFO

# Script de instalação para a VM que mede a disponibilidade durante a migração
# Deve ser adicionado no momento da criação da instancia (no openstack Console)
#       mas pode ser usado pelo Rally.
# Isso evita que tenha-se que criar uma snapshot customizada

upstart() {
# Vars
	IPERF="iperf3"
	IPERF_I=$IPERF"_3.1.3-1_amd64.deb"
	LIBIPERF="libiperf0"
	LIBIPERF_I=$LIBIPERF"_3.1.3-1_amd64.deb"
	LOCAL_I="/home/ubuntu"

# Install iperf:
	sudo apt-get remove $IPERF3 $LIBIPERF
	wget https://iperf.fr/download/ubuntu/$LIBIPERF_I
	wget https://iperf.fr/download/ubuntu/$IPERF_I
	sudo chmod +x $LIBIPERF_I $IPERF_I
	sudo dpkg -i $LIBIPERF_I $IPERF_I
	rm $LIBIPERF_I $IPERF_I

# Install NetData
	sudo apt-get update && sudo apt-get upgrade -y
        wget https://my-netdata.io/kickstart-static64.sh
        chmod +x $LOCAL_I/kickstart-static64.sh 
        sh $LOCAL_I/kickstart-static64.sh --dont-wait

#	bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait

# Install stress:
	sudo apt-get install stress -y

}

execute(){
	stress --cpu 8 --io 4 --vm 2 --vm-bytes 128M -hdd 4 --timeout 600s&
	
	python $LOCAL_I/socketLAB.py
	iperf3 -s -p 80
}

case "$1" in
  start)
	upstart 1
	execute 1
	;;
  stop)
	;;

  reload|force-reload)
	;;

  restart)
	;;

esac

exit 0
